### PR TITLE
Store data/book label

### LINKED ISSUE #10: [2pt] All data should be preserved by saving collections in .json files.
All data should be preserved by saving collections in .json files.

### PR DESCRIPTION
**Pull request by omarsalem7**
## What does this PR do?

This PR is raised to store data in files. This closes #10

## Description of the task to be completed

- [x] create `books.json` file to store data
- [x] create `labels.json` file to store data

## How should it be tested

Clone the repository
```
git clone https://github.com/omarsalem7/Catalog-of-things.git
```
Navigate to the folder
```
cd Catalog-of-things
```
Checkout the branch
```
git checkout store-data/book-label
```

### CODE REVIEW

**Comment by BertrandConxy** [comment]
Good morning @omarsalem7. I am going to review your PR

**Review by BertrandConxy — APPROVED** [review]
# STATUS: APPROVED 🥇 🥇 🥇 
## Hello @omarsalem7 ✋ ,
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:   
Congratulations! 🎉 
Congratulations-Memes-FEATURED
## To Highlight 🦾 
✅ The data are being stored successfully
✅ The program is working well
✅ The requirement is well implemented
✅ Use of Ruby best practices
✅ all linter tests are passing too

### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**Review by BertrandConxy — COMMENTED** [review]
[OPTIONAL] I liked the way you reference a particular issue that is linked to this pull request 👍 
However, there is a way you can make that particular issue close automatically when this PR is closed too. It is by adding keywords like `close`, `closes`, `fix`, `fixes` just before the issue reference. Like in this way:
Review2
Therefore, I kindly recommend that you may add it in your next PR(s) because at the end of the day, we shall close all the issues.

**Comment by omarsalem7** [comment]
Thanks @BertrandConxy for this tip

**Pull request merged**
